package com.example.kotlintut.ui.theme

object Locales {
    val IT = mapOf(
        "app_name" to "Ristorante Totem",
        "home" to "Home",
        "favorites" to "Preferiti",
        "options" to "Opzioni",
        "login_register" to "Accedi / Registrati",
        "order_history" to "Storico Ordini",
        "logout" to "Logout",
        "welcome" to "Benvenuto!",
        "guest" to "Ospite",
        "what_to_order" to "Cosa vuoi ordinare?",
        "search_products" to "Cerca prodotti...",
        "no_products" to "Nessun prodotto trovato.",
        "details" to "Dettagli",
        "customize_order" to "Personalizza il tuo ordine",
        "add_to_cart" to "AGGIUNGI",
        "my_favorites" to "I miei Preferiti",
        "no_favorites" to "Non hai ancora aggiunto dei preferiti.",
        "aspect" to "Aspetto",
        "dark_mode" to "Tema Scuro",
        "toggle_dark_mode" to "Attiva/Disattiva il tema scuro",
        "language" to "Lingua",
        "app_language" to "Lingua Applicazione",
        "current_lang" to "Italiano",
        "cart" to "Carrello",
        "cart_empty" to "Il carrello è vuoto",
        "total" to "Totale",
        "proceed_to_checkout" to "PROCEDI AL CHECKOUT",
        "contact_info" to "Informazioni di Contatto",
        "guest_info_desc" to "Inserisci i tuoi dati per procedere come ospite",
        "full_name" to "Nome Completo",
        "email" to "Email",
        "continue_to_payment" to "CONTINUA AL PAGAMENTO",
        "payment" to "Pagamento",
        "total_to_pay" to "Totale da pagare",
        "choose_payment_method" to "Scegli metodo di pagamento",
        "credit_card" to "Carta di Credito",
        "card_number" to "Numero Carta",
        "expiry" to "Scadenza (MM/YY)",
        "cvv" to "CVV",
        "confirm_order" to "CONFERMA ORDINE",
        "order_received" to "Ricevuto",
        "order_preparing" to "In Preparazione",
        "order_ready" to "Pronto!",
        "order_status" to "Stato del tuo ordine",
        "back_to_home" to "TORNA ALLA HOME",
        "no_orders" to "Nessun ordine trovato",
        "order_id" to "Ordine #",
        "reorder" to "RIFAI ORDINE",
        "auth_title" to "Ristorante Totem",
        "auth_desc" to "Identificati per un'esperienza personalizzata",
        "login" to "ACCEDI",
        "register" to "REGISTRATI",
        "continue_as_guest" to "Continua come Ospite",
        "welcome_back" to "Bentornato!",
        "create_account" to "Crea Account",
        "username" to "Username",
        "password" to "Password",
        "registration" to "Registrazione",
        "password_requirements" to "Requisiti Password:",
        "req_length" to "Almeno 8 caratteri",
        "req_upper" to "Almeno una maiuscola",
        "req_lower" to "Almeno una minuscola",
        "req_digit" to "Almeno un numero",
        "req_symbol" to "Almeno un simbolo",
        "order_history_info" to "Per vedere dettagli dell'ordine e ripeterlo cliccare sull'ordine",
        "ok" to "OK",
        // Categories
        "Panini" to "Panini",
        "Primi" to "Primi",
        "Secondi" to "Secondi",
        "Bevande" to "Bevande",
        // Products
        "prod_hamburger" to "Hamburger Classico",
        "prod_cheeseburger" to "Cheeseburger",
        "prod_pizza" to "Pizza Margherita",
        "prod_pasta_al_pesto" to "Pasta al Pesto",
        "prod_pasta" to "Pasta al Pomodoro",
        "prod_lasagna" to "Lasagna alla Bolognese",
        "prod_cotoletta" to "Cotoletta alla Milanese",
        "prod_grigliata" to "Grigliata Mista",
        "prod_acqua" to "Acqua Naturale",
        "prod_coca" to "Coca Cola",
        "prod_fanta" to "Fanta",
        "prod_sprite" to "Sprite",
        "prod_fanta_zero" to "Fanta Zero",
        "prod_birra" to "Birra Ichnusa",
        "prod_chinotto" to "Chinotto",
        "prod_lemon_soda" to "Lemon Soda",
        "prod_oran_soda" to "Oran Soda",
        "prod_water" to "Acqua Frizzante",
        "prod_the_pesca" to "The alla Pesca",
        "prod_the_limone" to "The al Limone",
        // Descriptions
        "desc_hamburger" to "Carne di manzo, lattuga, pomodoro e salsa totem.",
        "desc_cheeseburger" to "Carne di manzo, cheddar fuso e cetriolini.",
        "desc_pizza" to "Pomodoro, mozzarella di bufala e basilico fresco.",
        "desc_pasta_al_pesto" to "Pasta fresca con pesto alla genovese artigianale.",
        "desc_pasta" to "Pasta al dente con salsa di pomodoro e basilico.",
        "desc_lasagna" to "Sfoglia fresca, ragù di carne e besciamella.",
        "desc_cotoletta" to "Cotoletta di pollo croccante con patatine fritte.",
        "desc_grigliata" to "Selezione di carni scelte alla brace.",
        "desc_acqua" to "Acqua minerale naturale 50cl.",
        "desc_coca" to "Coca Cola classica in lattina 33cl.",
        "desc_fanta" to "Fanta Orange in lattina 33cl.",
        "desc_sprite" to "Sprite in lattina 33cl.",
        "desc_fanta_zero" to "Fanta senza zuccheri aggiunti 33cl.",
        "desc_birra" to "Birra sarda non filtrata 33cl.",
        "desc_chinotto" to "Chinotto classico 33cl.",
        "desc_lemon_soda" to "Lemon Soda rinfrescante 33cl.",
        "desc_oran_soda" to "Oran Soda all'arancia 33cl.",
        "desc_water" to "Acqua minerale frizzante 50cl.",
        "desc_the_pesca" to "The freddo alla pesca 33cl.",
        "desc_the_limone" to "The freddo al limone 33cl."
    )

    val EN = mapOf(
        "app_name" to "Totem Restaurant",
        "home" to "Home",
        "favorites" to "Favorites",
        "options" to "Options",
        "login_register" to "Login / Register",
        "order_history" to "Order History",
        "logout" to "Logout",
        "welcome" to "Welcome!",
        "guest" to "Guest",
        "what_to_order" to "What would you like to order?",
        "search_products" to "Search products...",
        "no_products" to "No products found.",
        "details" to "Details",
        "customize_order" to "Customize your order",
        "add_to_cart" to "ADD",
        "my_favorites" to "My Favorites",
        "no_favorites" to "You haven't added any favorites yet.",
        "aspect" to "Appearance",
        "dark_mode" to "Dark Mode",
        "toggle_dark_mode" to "Toggle dark theme",
        "language" to "Language",
        "app_language" to "App Language",
        "current_lang" to "English",
        "cart" to "Cart",
        "cart_empty" to "The cart is empty",
        "total" to "Total",
        "proceed_to_checkout" to "PROCEED TO CHECKOUT",
        "contact_info" to "Contact Info",
        "guest_info_desc" to "Enter your details to proceed as a guest",
        "full_name" to "Full Name",
        "email" to "Email",
        "continue_to_payment" to "CONTINUE TO PAYMENT",
        "payment" to "Payment",
        "total_to_pay" to "Total to pay",
        "choose_payment_method" to "Choose payment method",
        "credit_card" to "Credit Card",
        "card_number" to "Card Number",
        "expiry" to "Expiry (MM/YY)",
        "cvv" to "CVV",
        "confirm_order" to "CONFIRM ORDER",
        "order_received" to "Received",
        "order_preparing" to "Preparing",
        "order_ready" to "Ready!",
        "order_status" to "Your order status",
        "back_to_home" to "BACK TO HOME",
        "no_orders" to "No orders found",
        "order_id" to "Order #",
        "reorder" to "REORDER",
        "auth_title" to "Totem Restaurant",
        "auth_desc" to "Identify yourself for a personalized experience",
        "login" to "LOGIN",
        "register" to "REGISTER",
        "continue_as_guest" to "Continue as Guest",
        "welcome_back" to "Welcome back!",
        "create_account" to "Create Account",
        "username" to "Username",
        "password" to "Password",
        "registration" to "Registration",
        "password_requirements" to "Password Requirements:",
        "req_length" to "At least 8 characters",
        "req_upper" to "At least one uppercase",
        "req_lower" to "At least one lowercase",
        "req_digit" to "At least one number",
        "req_symbol" to "At least one symbol",
        "order_history_info" to "To see order details and repeat it, click on the order",
        "ok" to "OK",
        // Categories
        "Panini" to "Sandwiches",
        "Primi" to "First Courses",
        "Secondi" to "Main Courses",
        "Bevande" to "Drinks",
        // Products
        "prod_hamburger" to "Classic Hamburger",
        "prod_cheeseburger" to "Cheeseburger",
        "prod_pizza" to "Margherita Pizza",
        "prod_pasta_al_pesto" to "Pasta with Pesto",
        "prod_pasta" to "Pasta with Tomato Sauce",
        "prod_lasagna" to "Bolognese Lasagna",
        "prod_cotoletta" to "Milanese Cutlet",
        "prod_grigliata" to "Mixed Grill",
        "prod_acqua" to "Still Water",
        "prod_coca" to "Coca Cola",
        "prod_fanta" to "Fanta",
        "prod_sprite" to "Sprite",
        "prod_fanta_zero" to "Fanta Zero",
        "prod_birra" to "Ichnusa Beer",
        "prod_chinotto" to "Chinotto",
        "prod_lemon_soda" to "Lemon Soda",
        "prod_oran_soda" to "Oran Soda",
        "prod_water" to "Sparkling Water",
        "prod_the_pesca" to "Peach Ice Tea",
        "prod_the_limone" to "Lemon Ice Tea",
        // Descriptions
        "desc_hamburger" to "Beef, lettuce, tomato and totem sauce.",
        "desc_cheeseburger" to "Beef, melted cheddar and pickles.",
        "desc_pizza" to "Tomato, buffalo mozzarella and fresh basil.",
        "desc_pasta_al_pesto" to "Fresh pasta with artisanal Genovese pesto.",
        "desc_pasta" to "Al dente pasta with tomato sauce and basil.",
        "desc_lasagna" to "Fresh pasta sheets, meat ragu and bechamel.",
        "desc_cotoletta" to "Crispy chicken cutlet with french fries.",
        "desc_grigliata" to "Selection of premium grilled meats.",
        "desc_acqua" to "Still mineral water 50cl.",
        "desc_coca" to "Classic Coca Cola can 33cl.",
        "desc_fanta" to "Fanta Orange can 33cl.",
        "desc_sprite" to "Sprite can 33cl.",
        "desc_fanta_zero" to "Fanta sugar-free can 33cl.",
        "desc_birra" to "Unfiltered Sardinian beer 33cl.",
        "desc_chinotto" to "Classic Chinotto 33cl.",
        "desc_lemon_soda" to "Refreshing Lemon Soda 33cl.",
        "desc_oran_soda" to "Orange Oran Soda 33cl.",
        "desc_water" to "Sparkling mineral water 50cl.",
        "desc_the_pesca" to "Peach iced tea 33cl.",
        "desc_the_limone" to "Lemon iced tea 33cl."
    )

    /**
     * Recupera una stringa localizzata data una chiave e la lingua.
     */
    fun getString(key: String, lang: String): String {
        val map = if (lang == "EN") EN else IT
        return map[key] ?: key
    }
}
